import { Theme } from '../types';

export const THEMES: Theme[] = [
  {
    name: 'White',
    background: 'bg-white',
    text: 'text-black',
    textDemo: 'bg-black',
    accent: 'bg-black',
    accentText: 'text-white',
    hoverAccent: 'hover:bg-gray-800',
    hoverAccentText: 'hover:text-gray-200',
  },
  {
    name: 'Black',
    background: 'bg-black',
    text: 'text-white',
    textDemo: 'bg-white',
    accent: 'bg-white',
    accentText: 'text-black',
    hoverAccent: 'hover:bg-gray-200',
    hoverAccentText: 'hover:text-gray-800',
  },
  {
    name: 'Pastel',
    background: 'bg-[#FAFAFA]',
    text: 'text-[#222222]',
    textDemo: 'bg-[#222222]',
    accent: 'bg-[#FFDAB9]',
    accentText: 'text-[#222222]',
    hoverAccent: 'hover:bg-[#FFC0CB]',
    hoverAccentText: 'hover:text-[#111111]',
  },
  {
    name: 'Vintage',
    background: 'bg-[#F5F5DC]',
    text: 'text-[#3A3A3A]',
    textDemo: 'bg-[#3A3A3A]',
    accent: 'bg-[#D3B987]',
    accentText: 'text-[#3A3A3A]',
    hoverAccent: 'hover:bg-[#C5A86E]',
    hoverAccentText: 'hover:text-[#2a2a2a]',
  },
  {
    name: 'Retro',
    background: 'bg-[#E6E6FA]',
    text: 'text-[#111111]',
    textDemo: 'bg-[#111111]',
    accent: 'bg-[#f18f68]',
    accentText: 'text-[#FFFFFF]',
    hoverAccent: 'hover:bg-[#FF7F50]',
    hoverAccentText: 'hover:text-[#FFFFFF]',
  },
  {
    name: 'Minimalist',
    background: 'bg-[#FFFFFF]',
    text: 'text-[#000000]',
    textDemo: 'bg-[#000000]',
    accent: 'bg-[#AFEEEE]',
    accentText: 'text-[#000000]',
    hoverAccent: 'hover:bg-[#40E0D0]',
    hoverAccentText: 'hover:text-[#111111]',
  },
  {
    name: 'Modern',
    background: 'bg-[#1A1A1A]',
    text: 'text-[#EAEAEA]',
    textDemo: 'bg-[#EAEAEA]',
    accent: 'bg-[#518bc8]', // Измененный цвет синего
    accentText: 'text-[#EAEAEA]',
    hoverAccent: 'hover:bg-[#447dba]',
    hoverAccentText: 'hover:text-[#EAEAEA]',
  },
  {
    name: 'Classic',
    background: 'bg-[#FAEBD7]',
    text: 'text-[#333333]',
    textDemo: 'bg-[#333333]',
    accent: 'bg-[#FF6F61]',
    accentText: 'text-[#FFFFFF]',
    hoverAccent: 'hover:bg-[#fb5342]',
    hoverAccentText: 'hover:text-[#FFFFFF]',
  },
  {
    name: 'Elegant',
    background: 'bg-[#2C2C2C]',
    text: 'text-[#D3D3D3]',
    textDemo: 'bg-[#D3D3D3]',
    accent: 'bg-[#9370DB]',
    accentText: 'text-[#FFFFFF]',
    hoverAccent: 'hover:bg-[#8A2BE2]',
    hoverAccentText: 'hover:text-[#cccccc]',
  },
  {
    name: 'Sophisticated',
    background: 'bg-[#F0FFF0]',
    text: 'text-[#2E2E2E]',
    textDemo: 'bg-[#2E2E2E]',
    accent: 'bg-[#98FB98]',
    accentText: 'text-[#2E2E2E]',
    hoverAccent: 'hover:bg-[#b5f2b5]',
    hoverAccentText: 'hover:text-[#111111]',
  },
  {
    name: 'Urban',
    background: 'bg-[#2F4F4F]',
    text: 'text-[#FFFFFF]',
    textDemo: 'bg-[#FFFFFF]',
    accent: 'bg-[#FFE135]',
    accentText: 'text-[#2F4F4F]',
    hoverAccent: 'hover:bg-[#FFD700]',
    hoverAccentText: 'hover:text-[#243c3c]',
  },
  {
    name: 'Artistic',
    background: 'bg-[#FFF0F5]',
    text: 'text-[#3B3B3B]',
    textDemo: 'bg-[#3B3B3B]',
    accent: 'bg-[#FFB6C1]',
    accentText: 'text-[#3B3B3B]',
    hoverAccent: 'hover:bg-[#FF69B4]',
    hoverAccentText: 'hover:text-[#2a2a2a]',
  },
];
